name: Deploy to CapRover

on:
  push:
    branches:
      - production  # Deploy hanya jalan saat push ke branch production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: 'https://captain.apps.arulize.com'
          app: 'my-solona-bot'
          token: ${{ secrets.CAPROVER_TOKEN }}
